title: kutils 技术文档
baseurl: "/kutils/docs"
markdown: kramdown
theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-remote-theme
remote_theme: pages-themes/hacker@v0.2.0
exclude: ["yardoc", "Gemfile", "Gemfile.lock"]
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..3
show_downloads: false