name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Build YARD API docs
        run: |
          bundle exec yard doc --output-dir public
      # - name: Build Jekyll Markdown docs
      #   run: |
      #     bundle config set --local path 'vendor/bundle'
      #     gem install jekyll bundler
      #     cd docs
      #     bundle install
      #     bundle exec jekyll build -d ../public/docs
      #     cd ..
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public