name: Security

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  bundler-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install dependencies
        run: |
          gem install bundler-audit
          bundle install --jobs 4 --retry 3
      - name: Run bundler-audit
        run: bundler-audit check --update

  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        uses: dependabot/fetch-metadata@v2